/*
 * @Author: Frozen (https://github.com/AlterFrozen)
 * @Date: 2022-09-12 17:07:31
 * @LastEditTime: 2022-10-23 19:43:12
 * @LastEditors: Please set LastEditors
 * @Description: A collection of bitwise operation functions (C++20)

███████╗██████╗  ██████╗ ███████╗███████╗███╗   ██╗    ██╗   ██╗████████╗██╗██╗     ███████╗
██╔════╝██╔══██╗██╔═══██╗╚══███╔╝██╔════╝████╗  ██║    ██║   ██║╚══██╔══╝██║██║     ██╔════╝
█████╗  ██████╔╝██║   ██║  ███╔╝ █████╗  ██╔██╗ ██║    ██║   ██║   ██║   ██║██║     ███████╗
██╔══╝  ██╔══██╗██║   ██║ ███╔╝  ██╔══╝  ██║╚██╗██║    ██║   ██║   ██║   ██║██║     ╚════██║
██║     ██║  ██║╚██████╔╝███████╗███████╗██║ ╚████║    ╚██████╔╝   ██║   ██║███████╗███████║
╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═══╝     ╚═════╝    ╚═╝   ╚═╝╚══════╝╚══════╝
                                                                                            
[Logo Generated By]>> http://patorjk.com/software/taag/ 
*/

#ifndef _FUBITS_HPP_
#define _FUBITS_HPP_

#include <bit>
#include <cassert>
#include <concepts>

namespace FU
{
    /**
     * Returns the lowest 1-bit of num (e.g. num = B110, return = B010)
     * @param {int} num
     * @return {int} The lowest 1-bit of num
     */
    template<std::integral T>
    int lowestOneBit(T num) 
    {
        return num & (~num + 1);
    }

    /**
     * Returns the number of leading 0-bits in num, starting at the most significant bit position. If num is 0, the result is undefined.
     * @param {int} num
     * @return {int} The number of leading 0-bits in num
     */    
    int leadingZeroBits(unsigned int num)
    {
        assert(num != 0 && "leadingZeroBits()>> The result is undefined when num is 0!");
        return std::countl_zero(num);
    }

    /**
     * Returns the number of trailing 0-bits in num, starting at the least significant bit position. If num is 0, the result is undefined.
     * @param {int} num
     * @return {int} The number of trailing 0-bits in num
     */    
    int trailingZeroBits(unsigned int num)
    {
        assert(num != 0 && "trailingZeroBits()>> The result is undefined when num is 0!");
        return std::countr_zero(num);
    }

    /**
     * Returns the number of 1-bits in num.
     * @param {unsigned int} num
     * @return {int} the number of 1-bits in num.
     */    
    int countOneBits(unsigned int num)
    {
        return std::popcount(num);
    }

    /**
     * Returns the bit-reversed num
     * @param {uint32_t} num
     * @return {uint32_t} The bit-reversed num.
     */    
    uint32_t reverseBits(uint32_t num)
    {
        num = num >> 1 & 0x55555555 | (num & 0x55555555) << 1;
        num = num >> 2 & 0x33333333 | (num & 0x33333333) << 2;
        num = num >> 4 & 0x0f0f0f0f | (num & 0x0f0f0f0f) << 4;
        num = num >> 8 & 0x00ff00ff | (num & 0x00ff00ff) << 8;
        return num >> 16 | num << 16;
    }

    /**
     * Returns the Endianness-reversed num
     * @param {uint32_t} num
     * @return {uint32_t} The Endianness-reversed num.
     */
    uint32_t reverseEndianness(uint32_t num)
    {
        num = num >> 8 & 0x00ff00ff | (num & 0x00ff00ff) << 8;
        return num >> 16 | num << 16;
    }
}

#endif